# Generated by Django 5.0.6 on 2024-07-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('motif', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Bodies Types',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('japanese_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(blank=True, choices=[('MX', 'Mexico'), ('JP', 'Japan'), ('BQ', 'Caribbean'), ('FR', 'France'), ('SE', 'Sweden'), ('EG', 'Egypt'), ('CZ', 'Czechia'), ('US', 'United States of America'), ('IS', 'Iceland'), ('KE', 'Kenya')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('letter', models.CharField(max_length=1)),
                ('attribute', models.CharField(max_length=255)),
                ('nature', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medal',
                'verbose_name_plural': 'Medals',
                'ordering': ('letter',),
            },
        ),
        migrations.CreateModel(
            name='Medarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tinpet', models.CharField(choices=[('', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_no', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('r_arm', models.CharField(max_length=255)),
                ('l_arm', models.CharField(max_length=255)),
                ('legs', models.CharField(max_length=255)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medarots', to='characters.body')),
                ('medal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medarots', to='characters.medal')),
                ('medarotter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medarots', to='characters.character')),
            ],
            options={
                'verbose_name_plural': 'Medarots',
                'ordering': ['body__type'],
            },
        ),
    ]
