# Generated by Django 5.0.6 on 2024-07-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ('type',), 'verbose_name': 'Body Type', 'verbose_name_plural': 'Body Types'},
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character_image'),
        ),
        migrations.AddField(
            model_name='medal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medal_image'),
        ),
        migrations.AddField(
            model_name='medarot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medarot_image'),
        ),
        migrations.AddField(
            model_name='medarot',
            name='japanese_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='japanese_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
