# Generated by Django 5.0.6 on 2024-07-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_body_options_character_image_medal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='japanese_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
