# Generated by Django 5.0.6 on 2024-07-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_medal_japanese_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
