# Generated by Django 5.0.6 on 2024-07-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
