# Generated by Django 5.0.6 on 2024-07-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medarot',
            name='medarotter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medarots', to='characters.character'),
        ),
    ]
