# Generated by Django 5.0.6 on 2024-07-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('episode_image', models.ImageField(blank=True, null=True, upload_to='episode_image')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
